# Generated by Django 3.2.3 on 2022-06-10 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='mobile',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
    ]
