# Generated by Django 3.2.18 on 2024-11-19 13:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_alter_booking_mobile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='bookingDate',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Book Date'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='mobile',
            field=models.CharField(max_length=10, validators=[django.core.validators.MinLengthValidator(10)], verbose_name='Client Mobile'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='serviceDescriptions',
            field=models.TextField(verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='servicingDate',
            field=models.DateField(verbose_name='Service Date'),
        ),
        migrations.AlterField(
            model_name='mechanic',
            name='yoe',
            field=models.CharField(max_length=3, verbose_name='Year of Experience'),
        ),
    ]
